import sqlalchemy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String,Boolean, create_engine
from sqlalchemy.dialects.mysql.base import DECIMAL
from sqlalchemy.dialects.mysql import DATETIME
from sqlalchemy.orm import sessionmaker

Base = declarative_base()
class Game(Base):
    __tablename__='Game'
    GameID = Column(Integer, primary_key=True)
    Season = Column(Integer)
    SeasonType = Column(Integer)
    Status = Column(String(20))
    Day = Column(DATETIME)
    DateTime = Column(DATETIME)
    AwayTeam = Column(String(10))
    HomeTeam = Column(String(10))
    AwayTeamID = Column(Integer)
    HomeTeamID = Column(Integer)
    RescheduledGameID = Column(Integer)
    StadiumID = Column(Integer)
    Channel = Column(String(10))
    Inning = Column(Integer)
    InningHalf = Column(String(1))
    AwayTeamRuns = Column(Integer)
    HomeTeamRuns = Column(Integer)
    AwayTeamHits = Column(Integer)
    HomeTeamHits = Column(Integer)
    AwayTeamErrors = Column(Integer)
    HomeTeamErrors = Column(Integer)
    WinningPitcherID = Column(Integer)
    LosingPitcherID = Column(Integer)
    SavingPitcherID = Column(Integer)
    Attendance = Column(Integer)
    AwayTeamProbablePitcherID = Column(Integer)
    HomeTeamProbablePitcherID = Column(Integer)
    Outs = Column(Integer)
    Balls = Column(Integer)
    Strikes = Column(Integer)
    CurrentPitcherID = Column(Integer)
    CurrentHitterID = Column(Integer)
    AwayTeamStartingPitcherID = Column(Integer)
    HomeTeamStartingPitcherID = Column(Integer)
    CurrentPitchingTeamID = Column(Integer)
    CurrentPitchingTeamID = Column(Integer)
    CurrentPitchingTeamID = Column(Integer)
    CurrenthittingTeamID = Column(Integer)
    PointSpread = Column(DECIMAL(11,8))
    OverUnder = Column(DECIMAL(11,8))
    AwayTeamMoneyLine = Column(Integer)
    HomeTeamMoneyLine = Column(Integer)
    ForecastTempLow = Column(Integer)
    ForecastTempHigh = Column(Integer)
    ForeCastDescription =Column(String(50))
    ForecastWindChill = Column(Integer)
    ForecastWindSpeed = Column(Integer)
    ForeCastWindDirection = Column(Integer)
    RescheduledFromGameID = Column(Integer)
    RunnerOnFirst = Column(Boolean)
    RunnerOnSecond = Column(Boolean)
    RunnerOnThird = Column(Boolean)
    AwayTeamStartingPitcher = Column(String(50))
    HomeTeamStartingPitcher = Column(String(50))
    CurrentPitcher = Column(String(50))
    CurrentHitter = Column(String(50))
    WinningPitcher = Column(String(50))
    LosingPitcher = Column(String(50))
    SavingPitcher = Column(String(50))
    DueUpHitterID1 = Column(Integer)
    DueUpHitterID2 = Column(Integer)
    DueUpHitterID3 = Column(Integer)
    GobalGameID = Column(Integer)
    PointSpreadAwayTeamMoneyLine = Column(Integer)
    PointSpreadHomeTeamMoneyLine = Column(Integer)
    LastPlay = Column(String(250))

    def __repr__(self):
        return '<Game: %r>'%(self.GameID)

engine = create_engine('mysql+pymysql://root:uerbc0707@localhost/baseball', echo = True)
Base.metadata.create_all(engine)



